export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"

export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST"
export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS"
export const MESSAGE_LIST_FAILED = "MESSAGE_LIST_FAILED"

export const MESSAGE_DELETE_REQUEST = "MESSAGE_DELETE_REQUEST"
export const MESSAGE_DELETE_SUCCESS = "MESSAGE_DELETE_SUCCESS"
export const MESSAGE_DELETE_FAILED = "MESSAGE_DELETE_FAILED"

export const MESSAGE_POST_REQUEST = "MESSAGE_POST_REQUEST"
export const MESSAGE_POST_SUCCESS = "MESSAGE_POST_SUCCESS"
export const MESSAGE_POST_FAILED = "MESSAGE_POST_FAILED"

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED"

export const DELETE_ACCOUNT_REQUEST = "DELETE_ACCOUNT_REQUEST"
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS"
export const DELETE_ACCOUNT_FAILED = "DELETE_ACCOUNT_FAILED"


export const UPDATE_PROFILE_PICTURE_REQUEST = "UPDATE_PROFILE_PICTURE_REQUEST"
export const UPDATE_PROFILE_PICTURE_SUCCESS = "UPDATE_PROFILE_PICTURE_SUCCESS"
export const UPDATE_PROFILE_PICTURE_FAILED = "UPDATE_PROFILE_PICTURE_FAILED"

export const CLEAR_PROFILE_ALERTS = "CLEAR_PROFILE_ALERTS"

export const LOG_OUT = "LOG_OUT"